RRTPlannerROS: {
  goal_tolerance: 0.20, # tolerance for the goal point

  rrt: {
    step: 0.15, # size of each step
    min_num_nodes: 10000, # minimal number of nodes it need to find a path until it accepts the path
    max_num_nodes: 50000, # maximal number of nodes it can have
    goal_bias: 0.45  # the probability of choosing the goal as the next node
  }
}