RRTPlannerROS: {
  goal_tolerance: 0.20, # tolerance for the goal point

  rrt: {
    step: 0.15, # size of each step
    min_num_nodes: 1000, # minimal number of nodes it need to find a path until it accepts the path
    max_num_nodes: 5000, # maximal number of nodes it can have
    goal_bias: 0.9,  # the probability of choosing the goal as the next node
    threshold: 120 # controls how much we should avoid the obstacles (the lower the more it avoids)
  }
}